server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  tomcat:
    relaxed-query-chars: [ '{','}' ]

spring:
  datasource:
    password: Goldenpuppy@2022
    url: jdbc:mysql://localhost:3306/fashiongallery-new?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dinukaekanayaka18@gmail.com
    password: zrvfiznobaxltkjm

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true


