server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8080
  tomcat:
    relaxed-query-chars: [ '{','}' ]

spring:
  datasource:
    url: jdbc:mysql://fashiondb:3306/fashiondb?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: dinukaekanayaka18@gmail.com
    password: krrbrykibkfniplq

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true


